### PR TITLE
fix: php version tag updated in the composer.json file and composer.p…

### PR DESCRIPTION
**Pull request by gilons**
…har added
In this PR, I did the necessary changes for the package to run with php8.0. please do check and merge it as possible

### CODE REVIEW

**Review by gdebrauwer — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!
Can you please remove the `composer.phar` file? That file is not needed.
Can you also update the "run tests" github flow, so the tests are run on PHP 8?

**Comment by gilons** [comment]
Ok

**Comment by gilons** [comment]
unfortunately, more work needs to be done to upgrade the whole repo to Laravel 8 also

**Comment by gilons** [comment]
Laravel 7.* is not compatible with PHP 8

**Comment by gdebrauwer** [comment]
PHP 8 support has been added by PR #17

**Pull request closed without merging**
